version: '3.7'
services:
  ignite-api:
    build:
      context: .
      dockerfile: backend.docker
    dns:
      - 8.8.8.8
      - 4.4.4.4
    ports:
      - ${API_PORT}:3000
    depends_on:
      - ignite-wallet-postgres
      - ignite-wallet-redis
    volumes:
      - /data/ignite-wallet/backend/logs:/app/logs
      - /app/node_modules
  ignite-wallet-postgres:
    init: true
    image: postgres:12.2-alpine
    volumes:
      - ignite-wallet-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
  ignite-wallet-pgadmin:
    init: true
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    depends_on:
      - ignite-wallet-postgres
  ignite-wallet-redis:
    build:
      context: .
      dockerfile: redis.docker
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - ignite-wallet-redis:/data
    healthcheck:
      test: redis-cli PING
      timeout: 3s
volumes:
  ignite-wallet-postgres:
  ignite-wallet-redis:
